version: '3.8'
services:
  python-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-backend
    ports:
      - "8000:8000"
    environment:
      - NEBIUS_KEY=${NEBIUS_KEY}
    networks:
      - sage-network
networks:
  sage-network:
    external: true