spring:
  application:
    name: The Sage
  datasource:
    url: jdbc:postgresql://localhost:5432/sagedb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/sage_db?authSource=admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: INFO
    com:
      hse:
        sage: DEBUG